### ISSUE TITLE
[BUG] Build error with new Qt 6.9 in fakevim

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#3258]
[Fix compile with Qt 6.9 (7abf8ae4) · Commits · Qt Project / qt-creator / qt-creator · GitLab](https://invent.kde.org/qt/qt-creator/qt-creator/-/commit/7abf8ae477bf051624041bc851db4e90e8392c8d)

```
libraries/fakevim/fakevim/fakevimhandler.cpp:1060:44: error: no matching member function for call to 'arg'
 1060 |             res += QStringLiteral("\\x%1").arg(c.unicode(), 2, 16, QLatin1Char('0'));
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~^~~
```
