### ISSUE TITLE
supported oc6 but how view in oc 6?

### ISSUE THREAD

**Issue by mckaygerhard** [pbek/QOwnNotes#3]
this great app are supported for oc 6, but there's and alternativa inside owncloud web insterface?

a mean there a equivalent with, against the ownnote? due ownnote does not install in oc6 so
.. so this app install in opc6 and that its ironic!

**Comment by pbek** [comment]
QOwnNotes is compatible with the default notes application of ownCloud, I'm not absolutely sure when the notes app was added to ownCloud, I will change the requirement to ownCloud 7 to be sure. Thank you for pointing that out!

**Comment by mckaygerhard** [comment]
hey.. u will drop support to oc6 .. what a puff! of course more easy to drop rather that make!

**Comment by pbek** [comment]
I think there is a misunderstanding. I'm not the maintainer of the ownCloud Notes app (of which I don't know in which version of ownCloud it was added). I'm the maintainer of the QOwnNotes app, what runs natively on Windows, Mac and Linux and uses ownCloud to to sync notes. These notes can be edited in the notes app of the ownCloud notes app. That's the magic.

**Comment by mckaygerhard** [comment]
ummm.. so this app does not nothing to do with owncloud property, its and desktop integration app ...

**Comment by pbek** [comment]
It allows to edit ownCloud notes on the desktop.

**Comment by mckaygerhard** [comment]
yes i know.. i linked this repo to an issue in the ownnote repo that request integration with other desktop apps, please this app does compile with qt 4.6.3? if yes i can use massively in my enterprise and made good aproach and Free propagandize this.

**Comment by pbek** [comment]
Which distribution runs exactly that version? Did you try checking out the code and firing up "qmake"?

**Comment by mckaygerhard** [comment]
arrggg install again qt4 libs lots of space .

ur proyect are very crappy, hard to mantain on console.. 

intranet@sysmail00:~/Devel/QOwnNotes/src$ qmake -makefile QOwnNotes.pro 
Project MESSAGE: RELEASE!
WARNING: Failure to find: libraries/hoedown/html_blocks.h

**Comment by mckaygerhard** [comment]
new with some fixeds now that:

```
intranet@sysmail00:~/Devel/QOwnNotes/src$ make
/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h
/usr/bin/uic-qt4 notediffdialog.ui -o ui_notediffdialog.h
/usr/bin/uic-qt4 aboutdialog.ui -o ui_aboutdialog.h
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I. -I. -o main.o main.cpp
In file included from main.cpp:1:
mainwindow.h:12:44: error: markdown-highlight/highlighter.h: No existe el fichero o el directorio
In file included from main.cpp:1:
mainwindow.h:61: error: ISO C++ forbids declaration of ‘HGMarkdownHighlighter’ with no type
mainwindow.h:61: error: expected ‘;’ before ‘*’ token
mainwindow.h:63: error: ISO C++ forbids initialization of member ‘noteTextEditIsInEditMode’
mainwindow.h:63: error: making ‘noteTextEditIsInEditMode’ static
mainwindow.h:63: error: ISO C++ forbids in-class initialization of non-const static member ‘noteTextEditIsInEditMode’
make: *** [main.o] Error 1
```

**Comment by mckaygerhard** [comment]
after reduce usage of C++ standar from 2011 to c99 (fobit initialization on headers files are not permited before 2009) got this:

```
mainwindow.cpp: In member function ‘void MainWindow::loadNoteDirectoryList()’:
mainwindow.cpp:128: error: ‘QSignalBlocker’ does not name a type
mainwindow.cpp:131: error: ‘QSignalBlocker’ does not name a type
```

this are only compilable with qt 4.8.2, u must reduce the requeriments to qt 4.6.3 and i'll redistribute in two distributions and added to one desktop project pia fundation in Venezuela and Bolivia

**Comment by pbek** [comment]
My build process calls `qmake QOwnNotes.pro -r -spec linux-g++-64`. Does this do anything useful on your system?

Thank you for your analysis!
Looks like quite some work, I'm open for git pull requests!

**Comment by mckaygerhard** [comment]
the last problem are not qmake call related, its about using newer C++ standar that permits initialize an var in the headers...
